### ISSUE TITLE
install guide for Mac - missing title between 3"bet" and 4:

### ISSUE THREAD

**Issue by abonas** [rotev/rails-girls-il#62]
this section is missing a title and a step number, so it looks like part of 3"bet", and not as if it's not relevant for both who did 3"alef" AND 3"bet" -  it made some participants who did 3"alef" to miss a step:

בדקי כי הכל עובד באופן תקין ע״י הרצה של פקודת יצירת האפליקציה:

**Comment by inbalg** [comment]
Fixed in the guides repo (https://github.com/rotev/railsgirls.github.com/pull/8)
